#!/bin/python3

import math
import os
import random
import re
import sys

def diagonalDifference(arr):
    diagonal1 = sum(arr[x][x] for x in range(n))
    diagonal2= sum(arr[x][n-1-x] for x in range(n))
    return abs(diagonal1-diagonal2)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
